apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-db-pv
  namespace: fastfood
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  
  storageClassName: local-storage       
  hostPath:
    path: "/mnt/data"                   