apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: users-db
  name: users-db-data
  namespace: fastfood
spec:
  storageClassName: local-storage 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 